use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target ‘xp’ do

pod "AFNetworking", '3.1.0'
#pod 'XMPPFramework', '~> 3.7.0'
# 4.0 Preview / Master Branch
pod 'XMPPFramework', :git => 'https://github.com/robbiehanson/XMPPFramework.git', :branch => 'master'

# XMPPFramework with Swift extensions
#pod 'XMPPFramework/Swift', :git => 'https://github.com/robbiehanson/XMPPFramework.git', :branch => 'master'
end
